### ISSUE TITLE
[Feature Request] URL Monitor

### ISSUE THREAD

**Issue by zero77** [Mika-/torrent-control#10]
Can you please add support for URL monitoring.
For example, if I was to click a link ending in .torrent or starting with magnet:?xt= it will automatically be sent to the configured torrent client.
Thank You

**Comment by Mika-** [comment]
Magnet urls are already being handled by the native protocol handler.

Automatic handling for all links would be nice, but the current web extension API doesn't yet have methods to add custom download targets.
This absense could be filled by parsing and rewriting links or blocking and matching requests. Both ways are hacky and slow down regular browsing. This also makes extension unpredictable, as there's no way to know if the link will match. There would also be many false positives and misses because of wide variety of url schemas on different sites.

Firefox 58 will be shipped soon and hopefully we will know soon if there are plans to extend the download API to allow custom handling by mime type, like the old one had.

**Comment by zero77** [comment]
I see, so it’s just a case of waiting for the custom handling by mime type API to be implemented. 
Do you know if it has been requested or if there are any plans to implement it.

**Comment by Mika-** [comment]
Relevant tickets in bugzilla are [1344648](https://bugzilla.mozilla.org/show_bug.cgi?id=1344648) and [1356397](https://bugzilla.mozilla.org/show_bug.cgi?id=1356397). Loosened content handler would allow detecting files with `application/x-bittorrent` mime automatically. Althought this doesn't help if server is missconfigured and responds torrents with generic `application/octet-stream` which needs action from the user to work properly.

**Comment by zero77** [comment]
So it looks like it's just a case of waiting for the right Apis to be implemented, although it could be a while.

**Comment by Mika-** [comment]
Mozilla has triaged and combined relevant tickets to [1457500](https://bugzilla.mozilla.org/show_bug.cgi?id=1457500). So this is slowly progressing.

**Comment by ziffusion** [comment]
What is the harm in at least handling urls with the .torrent suffix? That would cover a whole lot of links, with very little chance of a false positive. Will you consider a pull request for this? Seems like a small enough change.

**Comment by Mika-** [comment]
It looks like Mozillas progress on web extension apis has once again halted. I have some free time this weekend so I can make initial support.
Do you have more proposals for regexp filters other than `/\.torrent$/`?

**Comment by ziffusion** [comment]
I just sent you a pull request for this. See if you like it.

And if you have other ideas, would be interested in learning.

**Comment by Mika-** [comment]
Feature is now present in 0.2.1.
