### ISSUE TITLE
Since last update (0.2.40 from 19 October) adding new torrent as paused start the download 

### ISSUE THREAD

**Issue by shama84** [Mika-/torrent-control#170]
Hi, 

Using the option "Add torrent (paused)" with Qbittorrent 4.6.6 and 4.6.7 starts the download instead of adding it in paused state.
Using QBT webUI to add the torrent does not create the same issue. 
(I guess only the paused state is missing in the command line)

**Comment by Mika-** [comment]
This is because of qBittorrent 5.0 release introducing api changes (paused is now stopped). You can choose older qBittorrent version from the addons bittorrent client selection. Clients without version indicator try to be compatible with the latest versions, so they work for most people as their apps update.

**Comment by imaginesoft** [comment]
Thanks for pointing it out, i think i installed this extension like years ago and never paid any attention to the qbit version before

**Comment by shama84** [comment]
> This is because of qBittorrent 5.0 release introducing api changes (paused is now stopped). You can choose older qBittorrent version from the addons bittorrent client selection. Clients without version indicator try to be compatible with the latest versions, so they work for most people as their apps update.

Thank you for the quick update, this is it! I selected the correct version on the option and it fine again
Have a nice Sunday :)
