### ISSUE TITLE
RTorrent directory

### ISSUE THREAD

**Issue by 07416** [Mika-/torrent-control#57]
In "directories", do I have to add the path of the "session" directory — where torrents are saved — for RTorrent? [As noted in another issue](https://github.com/Mika-/torrent-control/issues/56), the `405: not allowed` error refers "that configured server address is pointing to a wrong directory.". My server host has hidden all folders outside of `files` and `watch`.

In [the Firefox add-ons page](https://addons.mozilla.org/en-US/firefox/addon/torrent-control/) screenshots the "directories" field is left empty. Is this configuration optional or mandatory for all clients?

**Comment by Mika-** [comment]
Directories allows you to specify download directories available on the server and make them selectable in addons context menu (Add torrent with path). This setting is optional and isn't even supported by many torrent clients.

Your problem is most likely a wrong path to rtorrent ui. eg. https://myserver.tld/ vs https://myserver.tld/username/rtorrent/ or wherever you have installed it.
