### ISSUE TITLE
[Bug] Torrents from private tracker no longer adding

### ISSUE THREAD

**Issue by Kopernikus1979** [Mika-/torrent-control#74]
Hi,

I was using torrent-control without any problems with Deluge and private & public trackers.
But now when I want to add a torrent from a private tracker I get one of those 2 errors:

"Failed to read torrent (Unknow type: text/html" or when it get's added I get the error "passkey incorrect".

Any idea?

**Comment by Mika-** [comment]
This is most likely a change in a way that specific site authenticates it's users. Sites using other methods than a get parameter or a cookie won't work.

Hopefully Mozilla gets their [content handler](https://bugzilla.mozilla.org/show_bug.cgi?id=1457500) support done at some point. As that would allow more realiable torrent detection after request completion and mime detection. Instead of current hacky url matching and request emulation style.

**Comment by ryanerwin** [comment]
Instead of relying on the Firefox content handler, what about making the whitelist customizable, so that any site that doesn't get picked up in the default whitelist could be easily added with a list of user defined regular expressions?

https://github.com/Mika-/torrent-control/blob/7ee96bd5339ec123325daa5420d6e12a046acae9/src/util.js#L172

**Comment by Mika-** [comment]
Private trackers should now work a lot better with the latest version
